# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# 'C:\Users\nmartyanov\AppData\Local\Programs\Python\Python310\Lib\site-packages\PyQt5\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import traceback

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot, QTimer, Qt
from PyQt5.QtWidgets import QFileDialog, QLabel

from main import save_file


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 238)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 110, 171, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.open_file)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 110, 171, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setDisabled(True)
        self.pushButton_2.clicked.connect(self.fill_file)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 621, 50))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setReadOnly(True)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 160, 590, 40))
        self.label.setObjectName("label")
        self.label.setAlignment(Qt.AlignRight)
        self.label.setHidden(True)
        self.label.setWordWrap(True)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.time = QTimer(MainWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Выберите файл"))
        self.pushButton_2.setText(_translate("MainWindow", "Заполнить"))
        self.label.setText(_translate("MainWindow", "TextLabel"))

    def open_file(self):
        self.file_name = QtWidgets.QFileDialog.getOpenFileName(None, "Open", "",
                                                               "Excel (*.xls *.xlsx)")
        if self.file_name[0] != '':
            self.lineEdit.setText(self.file_name[0])
            self.pushButton_2.setDisabled(False)

    def fill_file(self):
        try:
            if self.file_name[0] != '':
                # print(1/0)
                save_file(self.file_name[0])
                self.label.setHidden(False)
                self.label.setStyleSheet("color: green")
                self.label.setText('Done! Окно можно закрыть')
        except Exception as exc:
            # print(exc.__class__.__name__)
            self.label.setHidden(False)
            self.label.setStyleSheet(
                "background-color: yellow; color: red; border: 1px solid black;")
            if exc.__class__.__name__ == 'PermissionError':
                self.label.setText(f'Файл используется другой программой Ошибка:{exc.__class__.__name__}: {exc}')
            else:
                self.label.setText(f'Ошибка:{exc.__class__.__name__}: {exc}')


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
